# Generated by Django 4.1.2 on 2022-10-19 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20221018_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('doing', 'doing'), ('done', 'done')], default=datetime.datetime(2022, 10, 19, 15, 56, 49, 167235, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
    ]
