# Generated by Django 4.1.2 on 2022-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to='ocorrencia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('Suporte Técnico Desktop - No Local', 'Suporte Técnico Desktop - No Local'), ('Suporte Técnico Desktop - Remoto', 'Suporte Técnico Desktop - Remoto'), ('Configuração de email', 'Configuração de email'), ('Suporte/Manutenção de Notebook', 'Suporte/Manutenção de Notebook')], max_length=50, null=True),
        ),
    ]
