# Generated by Django 4.1.2 on 2022-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_ticket_image_ticket_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ocorrencia'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Moderada', 'Moderada'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Fazendo', 'Fazendo'), ('Feito', 'Feito'), ('Expirado', 'Expirado'), ('Pausado', 'Pausado')], default='Fazendo', max_length=8),
        ),
    ]
