# Generated by Django 4.1.2 on 2022-11-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessages_userprofile_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
